
name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.19.1]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          SMTP_HOST: ${{secrets.SMTP_HOST}}
          SMTP_PORT: ${{secrets.SMTP_PORT}}
          SMTP_USER: ${{secrets.SMTP_USER}}
          SMTP_PASS: ${{secrets.SMTP_PASS}}
          NEXT_PUBLIC_APP_URL: ${{secrets.NEXT_PUBLIC_APP_URL}}
          STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
          ENABLE_PAYMENTS: ${{secrets.ENABLE_PAYMENTS}}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present
    - name: Directory 
      run: cd /home/azamat/actions-runner/_work/Consultan/Consultan
    - run: pm2 restart 0 